# # 多语言支持
# 为了使用giscus,将languageCode改为了en zh-CN  https://github.com/CaiJimmy/hugo-theme-stack/issues/1096
# 原本是en-us zh-cn
en:
  languageName: "English"
  languageCode: "en"
  weight: 2
  contentDir: content/en
  languagedirection: "ltr"
  title: "Producthunt daily"
  params:
    description: "Share Producthunt's hottest content daily. Discover the latest mobile apps, websites, and technology products that everyone's talking about."
    sidebar:
      subtitle: Share Producthunt's hottest content daily
zh-cn:
  languageName: "中文"
  languageCode: "zh-CN"
  weight: 1
  contentDir: content/zh-cn
  languagedirection: "ltr"
  title: "产品猎人"
  params:
    description: "每天分享 Producthunt 最热门的内容。发现大家都在谈论的最新移动应用、网站和技术产品。"
    sidebar:
      subtitle: 每天分享 Producthunt 最热门的内容
# 西班牙语
es:
  languageName: "Español"
  languageCode: "es"
  weight: 4
  contentDir: content/es
  languagedirection: "ltr"
  title: "Producthunt diario"
  params:
    description: "Comparte diariamente el contenido más candente de Producthunt. Descubre las últimas aplicaciones móviles, sitios web y productos tecnológicos de los que todo el mundo está hablando."
    sidebar:
      subtitle: Comparte diariamente el contenido más candente de Producthunt
# 阿拉伯语
ar:
  languageName: "العربية"
  languageCode: "ar"
  weight: 5
  contentDir: content/ar
  languagedirection: "rtl"
  title: "منتج هانت اليومي"
  params:
    description: "شارك المحتوى الأكثر سخونة من Producthunt يوميًا. اكتشف أحدث التطبيقات والمواقع والمنتجات التكنولوجية التي يتحدث عنها الجميع."
    sidebar:
      subtitle: شارك المحتوى الأكثر سخونة من Producthunt يوميًا
